### ISSUE TITLE
Problems with inference using trained ckpt models

### ISSUE THREAD

**Issue by LuZhouyu1** [matval/wayfaster#3] opened 2024-08-08 12:28 UTC
Hi Mateus

When I tried to infer the trav_map using images and point cloud as input, I found that the trav_map is different after importing the same model. I'm finding these random deviations coming from the temporal_model module? I'm curious if this is a feature of the model itself or something wrong with the program. 

Looking forward to your answer!

**Comment by matval** [comment] 2024-08-12 17:15
Hi @LuZhouyu1,

WayFASTER is designed to produce consistent outputs for the same inputs. However, the discrepancies you're observing in the trav_map after importing the same model might be due to the stochastic nature of certain components in the temporal_model module, such as batch normalization, which can introduce variability during inference if not properly handled.

To ensure consistent results, please make sure you're calling `model.eval()` before running the network inference.

If you could provide more details or share a minimal reproducible example, I'd be happy to help further investigate the issue.

Best regards,
Mateus

**Comment by LuZhouyu1** [comment] 2024-08-20 05:55
Hi Mateus

Thank you for the reply. I already solved that problem. The problem is due to some naming issues with the temporal_model key.

**Comment by matval** [comment] 2024-08-20 20:37
Hi @LuZhouyu1 

I’m glad to hear you were able to solve the problem! Thanks for letting me know.

If you run into any other issues or have more questions, feel free to reach out.

I’ll go ahead and close this issue now.

Best regards,
Mateus

**Closed as completed by matval** 2024-08-20 20:37 UTC

**Comment by er1c-cartman** [comment] 2025-03-23 04:45
Hi. First, thank you for sharing your amazing work.
I'm studying learning models recently, so have less knowledge about it. 
If you can, can you share the inference code?

Best regards
